apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: movie-reco-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: movie
    isDefault: true
    editable: false

    secureJsonData:
      password: movie

    jsonData:
      database: movie_reco
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false